### ISSUE TITLE
v0.1 파일전송

### ISSUE THREAD

**Issue by ghost** [kimshzxc/swproject-team-4#1]
파일전송을 함에있어서 어디서 부터 어떻게 접근해야하는지 잘 모르겠습니다.  문자형 기반 파일들은 전송할수 있겠으나 소리, 동영상, 실행파일등 binary 기반의 파일들은 어떻게 접근해야 할지 잘 모르겠습니다. 도움 부탁드려요~

**Comment by goodgab** [comment]
c++환경에서 client에서 fopen 함수로 바이너리를 읽어 최대 1kb씩 파일을 끝까지 읽을 때 까지 sendto함수로 server 에 보낸다. server에서는 client에서 보내는 크기만큼 fopen 함수로 바이너리로 쓰고 client에서 전송이 끝났을 때 종료 메시지를 보내 server를 종료 시킨다.
