### ISSUE TITLE
C++에서 Java로 프로젝트 언어 변경은 어떤가요?

### ISSUE THREAD

**Issue by ghost** [kimshzxc/swproject-team-4#2]
프로젝트를 진행하다 보니 저희 조원모두 소켓 통신을 처음 해보는데 c++ 보다는 java 예제도 다양하고 쉬워서 처음 하는 저희조에 적합 할것 같습니다. 조원분들의 의견을 들어보고 말해주세요~

**Comment by kashrana4j** [comment]
I think working on JAVA is more comfortable than C++.

**Comment by kimshzxc** [comment]
저도 찾아보니까 자바가 이식성도 좋고 API도 잘되어있는거 같네요... 자바로 바꾸는거 찬성합니다 ㅎㅎ
