### ISSUE TITLE
시간측정이 제대로 되지 않는 오류가 있는것 같다.

### ISSUE THREAD

**Issue by kimshzxc** [kimshzxc/swproject-team-4#4]
시간측정이 정확히 되지 않는다. 

UDP와 TCP의 시간측정 방식이 다르다

방식을 하나로 통일해보자

**Comment by goodgab** [comment]
기존의 UDP통신은 클라이언트에서 패킷을 보낸고 나서 서버으로 부터 패킷을 기다리는 불필요한 과정이 있었는데 이 과정을 빼고나서 시간 측정이 제대로 되었다.
